// THIS FILE HAS BEEN AUTOGENERATED, DO NOT MODIFY
// Generated on Thu 2025/09/11 11:09:43
// To edit shaders, edit the files inside the `helpers/gfx/shader_src_dx11/` folder,
// then run `build_shaders.bat`

namespace gfx {
namespace shaders {

namespace vs_color3d_unlit {
const char* name = "vs_color3d_unlit";
#if __DEBUG
const char* binFile = "helpers/gfx/shader_src_dx11/vs_color3d_unlit.h";
const char* srcFile = "helpers/gfx/shader_src_dx11/vs_color3d_unlit.vs";
#endif // __DEBUG
#include "vs_color3d_unlit.h"
}

namespace vs_fullscreen_bufferless_clear_blit {
const char* name = "vs_fullscreen_bufferless_clear_blit";
#if __DEBUG
const char* binFile = "helpers/gfx/shader_src_dx11/vs_fullscreen_bufferless_clear_blit.h";
const char* srcFile = "helpers/gfx/shader_src_dx11/vs_fullscreen_bufferless_clear_blit.vs";
#endif // __DEBUG
#include "vs_fullscreen_bufferless_clear_blit.h"
}

namespace vs_fullscreen_bufferless_textured_blit {
const char* name = "vs_fullscreen_bufferless_textured_blit";
#if __DEBUG
const char* binFile = "helpers/gfx/shader_src_dx11/vs_fullscreen_bufferless_textured_blit.h";
const char* srcFile = "helpers/gfx/shader_src_dx11/vs_fullscreen_bufferless_textured_blit.vs";
#endif // __DEBUG
#include "vs_fullscreen_bufferless_textured_blit.h"
}

namespace ps_color3d_unlit {
const char* name = "ps_color3d_unlit";
#if __DEBUG
const char* binFile = "helpers/gfx/shader_src_dx11/ps_color3d_unlit.h";
const char* srcFile = "helpers/gfx/shader_src_dx11/ps_color3d_unlit.ps";
#endif // __DEBUG
#include "ps_color3d_unlit.h"
}

namespace ps_fullscreen_blit_clear_colored {
const char* name = "ps_fullscreen_blit_clear_colored";
#if __DEBUG
const char* binFile = "helpers/gfx/shader_src_dx11/ps_fullscreen_blit_clear_colored.h";
const char* srcFile = "helpers/gfx/shader_src_dx11/ps_fullscreen_blit_clear_colored.ps";
#endif // __DEBUG
#include "ps_fullscreen_blit_clear_colored.h"
}

namespace ps_fullscreen_blit_textured {
const char* name = "ps_fullscreen_blit_textured";
#if __DEBUG
const char* binFile = "helpers/gfx/shader_src_dx11/ps_fullscreen_blit_textured.h";
const char* srcFile = "helpers/gfx/shader_src_dx11/ps_fullscreen_blit_textured.ps";
#endif // __DEBUG
#include "ps_fullscreen_blit_textured.h"
}

namespace ps_fullscreen_blit_textured_depth {
const char* name = "ps_fullscreen_blit_textured_depth";
#if __DEBUG
const char* binFile = "helpers/gfx/shader_src_dx11/ps_fullscreen_blit_textured_depth.h";
const char* srcFile = "helpers/gfx/shader_src_dx11/ps_fullscreen_blit_textured_depth.ps";
#endif // __DEBUG
#include "ps_fullscreen_blit_textured_depth.h"
}

}} // gfx::shaders 
