// THIS FILE HAS BEEN AUTOGENERATED, DO NOT MODIFY
// Generated on Fri 09/05/2025 13:35:37
// To edit shaders, edit the files inside the `helpers\gfx\shader_src_dx11\` folder,
// then run `build_shaders.bat`

namespace gfx {
namespace shaders {

namespace vs_color3d_unlit {
const char* name = "vs_color3d_unlit";
#include "vs_color3d_unlit.h"
}

namespace vs_fullscreen_bufferless_clear_blit {
const char* name = "vs_fullscreen_bufferless_clear_blit";
#include "vs_fullscreen_bufferless_clear_blit.h"
}

namespace vs_fullscreen_bufferless_textured_blit {
const char* name = "vs_fullscreen_bufferless_textured_blit";
#include "vs_fullscreen_bufferless_textured_blit.h"
}

namespace ps_color3d_unlit {
const char* name = "ps_color3d_unlit";
#include "ps_color3d_unlit.h"
}

namespace ps_fullscreen_blit_clear_colored {
const char* name = "ps_fullscreen_blit_clear_colored";
#include "ps_fullscreen_blit_clear_colored.h"
}

namespace ps_fullscreen_blit_textured {
const char* name = "ps_fullscreen_blit_textured";
#include "ps_fullscreen_blit_textured.h"
}

namespace ps_fullscreen_blit_textured_depth {
const char* name = "ps_fullscreen_blit_textured_depth";
#include "ps_fullscreen_blit_textured_depth.h"
}

}} // gfx::shaders 
