// THIS FILE HAS BEEN AUTOGENERATED, DO NOT MODIFY
// Generated on Fri 09/05/2025 13:32:03
// To edit shaders, edit the files inside the `helpers\gfx\shader_src_gl33\` folder,
// then run `build_shaders.bat`

namespace gfx {
namespace shaders {

namespace vs_color3d_unlit {
const char* name = "vs_color3d_unlit";
const char* src = 
R"(
#version 330
#extension GL_ARB_separate_shader_objects : require

out gl_PerVertex
{
    vec4 gl_Position;
};

layout(std140) uniform type_PerGroup
{
    mat4 MVP;
} PerGroup;

layout(location = 0) in vec3 in_var_POSITION;
layout(location = 1) in vec4 in_var_COLOR;
layout(location = 0) out vec4 varying_COLOR;

void main()
{
    varying_COLOR = in_var_COLOR;
    gl_Position = PerGroup.MVP * vec4(in_var_POSITION, 1.0);
}
)";
}

namespace vs_fullscreen_bufferless_clear_blit {
const char* name = "vs_fullscreen_bufferless_clear_blit";
const char* src = 
R"(
#version 330
#extension GL_ARB_separate_shader_objects : require

void main()
{
    float x = -1.0 + float((gl_VertexID & 1) << 2);
    float y = 1.0 - float((gl_VertexID & 2) << 1);
    gl_Position = vec4(x, y, 1.0, 1.0); // clear depth
})";
}

namespace vs_fullscreen_bufferless_textured_blit {
const char* name = "vs_fullscreen_bufferless_textured_blit";
const char* src = 
R"(
#version 330
#extension GL_ARB_separate_shader_objects : require

layout(location = 0) out vec2 varying_TEXCOORD;
 
void main()
{
    float x = -1.0 + float((gl_VertexID & 1) << 2);
    float y = 1.0 - float((gl_VertexID & 2) << 1);
    varying_TEXCOORD.x = (x+1.0)*0.5;
    varying_TEXCOORD.y = (y+1.0)*0.5;
    gl_Position = vec4(x, y, 0, 1);
}
)";
}

namespace ps_color3d_unlit {
const char* name = "ps_color3d_unlit";
const char* src = 
R"(
#version 330
#extension GL_ARB_separate_shader_objects : require

layout(location = 0) in vec4 varying_COLOR;
layout(location = 0) out vec4 out_var_SV_TARGET;

void main()
{
    out_var_SV_TARGET = varying_COLOR;
}
)";
}

namespace ps_fullscreen_blit_clear_colored {
const char* name = "ps_fullscreen_blit_clear_colored";
const char* src = 
R"(
#version 330
#extension GL_ARB_separate_shader_objects : require

layout(std140) uniform type_BlitColor
{
    vec4 color;
} BlitColor;

layout(location = 0) in vec2 varying_TEXCOORD;
layout(location = 0) out vec4 out_var_SV_TARGET;

void main()
{
    out_var_SV_TARGET = BlitColor.color;
}
)";
}

namespace ps_fullscreen_blit_textured {
const char* name = "ps_fullscreen_blit_textured";
const char* src = 
R"(
#version 330
#extension GL_ARB_separate_shader_objects : require

uniform sampler2D texSrc;

layout(location = 0) in vec2 varying_TEXCOORD;
layout(location = 0) out vec4 out_var_SV_TARGET;

void main()
{
    vec4 diffuse = texture(texSrc, varying_TEXCOORD).rgba;
    out_var_SV_TARGET = diffuse.rgba;
}
)";
}

namespace ps_fullscreen_blit_textured_depth {
const char* name = "ps_fullscreen_blit_textured_depth";
const char* src = 
R"(
#version 330
#extension GL_ARB_separate_shader_objects : require

uniform sampler2D texSrc;
uniform sampler2D depthSrc;

layout(location = 0) in vec2 varying_TEXCOORD;
layout(location = 0) out vec4 out_var_SV_TARGET;

void main()
{
    vec4 diffuse = texture(texSrc, varying_TEXCOORD).rgba;
    float depth = texture(depthSrc, varying_TEXCOORD).r;
    out_var_SV_TARGET = diffuse.rgba;
    gl_FragDepth = depth;
}
)";
}

}} // gfx::shaders 
