// THIS FILE HAS BEEN AUTOGENERATED, DO NOT MODIFY
// Generated on Fri 09/05/2025 13:35:37
// To edit shaders, edit the files inside the `shader_src_dx11\` folder,
// then run `build_shaders.bat`

namespace gfx {
namespace shaders {

namespace vs_3d_base {
const char* name = "vs_3d_base";
#include "vs_3d_base.h"
}

namespace vs_3d_instanced_base {
const char* name = "vs_3d_instanced_base";
#include "vs_3d_instanced_base.h"
}

namespace vs_color2d_base {
const char* name = "vs_color2d_base";
#include "vs_color2d_base.h"
}

namespace vs_color3d_base {
const char* name = "vs_color3d_base";
#include "vs_color3d_base.h"
}

namespace vs_color3d_skinned_base {
const char* name = "vs_color3d_skinned_base";
#include "vs_color3d_skinned_base.h"
}

namespace vs_textured3d_base {
const char* name = "vs_textured3d_base";
#include "vs_textured3d_base.h"
}

namespace vs_textured3d_skinned_base {
const char* name = "vs_textured3d_skinned_base";
#include "vs_textured3d_skinned_base.h"
}

namespace ps_fullscreen_blit_sdf {
const char* name = "ps_fullscreen_blit_sdf";
#include "ps_fullscreen_blit_sdf.h"
}

namespace ps_textured3dalphaclip_base {
const char* name = "ps_textured3dalphaclip_base";
#include "ps_textured3dalphaclip_base.h"
}

namespace ps_textured3d_base {
const char* name = "ps_textured3d_base";
#include "ps_textured3d_base.h"
}

}} // gfx::shaders 
