// THIS FILE HAS BEEN AUTOGENERATED, DO NOT MODIFY
// Generated on Thu 2025/09/11 11:09:43
// To edit shaders, edit the files inside the `shader_src_dx11/` folder,
// then run `build_shaders.bat`

namespace gfx {
namespace shaders {

namespace vs_3d_base {
const char* name = "vs_3d_base";
#if __DEBUG
const char* binFile = "shader_src_dx11/vs_3d_base.h";
const char* srcFile = "shader_src_dx11/vs_3d_base.vs";
#endif // __DEBUG
#include "vs_3d_base.h"
}

namespace vs_3d_instanced_base {
const char* name = "vs_3d_instanced_base";
#if __DEBUG
const char* binFile = "shader_src_dx11/vs_3d_instanced_base.h";
const char* srcFile = "shader_src_dx11/vs_3d_instanced_base.vs";
#endif // __DEBUG
#include "vs_3d_instanced_base.h"
}

namespace vs_color2d_base {
const char* name = "vs_color2d_base";
#if __DEBUG
const char* binFile = "shader_src_dx11/vs_color2d_base.h";
const char* srcFile = "shader_src_dx11/vs_color2d_base.vs";
#endif // __DEBUG
#include "vs_color2d_base.h"
}

namespace vs_color3d_base {
const char* name = "vs_color3d_base";
#if __DEBUG
const char* binFile = "shader_src_dx11/vs_color3d_base.h";
const char* srcFile = "shader_src_dx11/vs_color3d_base.vs";
#endif // __DEBUG
#include "vs_color3d_base.h"
}

namespace vs_color3d_skinned_base {
const char* name = "vs_color3d_skinned_base";
#if __DEBUG
const char* binFile = "shader_src_dx11/vs_color3d_skinned_base.h";
const char* srcFile = "shader_src_dx11/vs_color3d_skinned_base.vs";
#endif // __DEBUG
#include "vs_color3d_skinned_base.h"
}

namespace vs_textured3d_base {
const char* name = "vs_textured3d_base";
#if __DEBUG
const char* binFile = "shader_src_dx11/vs_textured3d_base.h";
const char* srcFile = "shader_src_dx11/vs_textured3d_base.vs";
#endif // __DEBUG
#include "vs_textured3d_base.h"
}

namespace vs_textured3d_skinned_base {
const char* name = "vs_textured3d_skinned_base";
#if __DEBUG
const char* binFile = "shader_src_dx11/vs_textured3d_skinned_base.h";
const char* srcFile = "shader_src_dx11/vs_textured3d_skinned_base.vs";
#endif // __DEBUG
#include "vs_textured3d_skinned_base.h"
}

namespace ps_fullscreen_blit_sdf {
const char* name = "ps_fullscreen_blit_sdf";
#if __DEBUG
const char* binFile = "shader_src_dx11/ps_fullscreen_blit_sdf.h";
const char* srcFile = "shader_src_dx11/ps_fullscreen_blit_sdf.ps";
#endif // __DEBUG
#include "ps_fullscreen_blit_sdf.h"
}

namespace ps_textured3dalphaclip_base {
const char* name = "ps_textured3dalphaclip_base";
#if __DEBUG
const char* binFile = "shader_src_dx11/ps_textured3dalphaclip_base.h";
const char* srcFile = "shader_src_dx11/ps_textured3dalphaclip_base.ps";
#endif // __DEBUG
#include "ps_textured3dalphaclip_base.h"
}

namespace ps_textured3d_base {
const char* name = "ps_textured3d_base";
#if __DEBUG
const char* binFile = "shader_src_dx11/ps_textured3d_base.h";
const char* srcFile = "shader_src_dx11/ps_textured3d_base.ps";
#endif // __DEBUG
#include "ps_textured3d_base.h"
}

}} // gfx::shaders 
